GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/1

###

GET http://localhost:3001/info

###

DELETE http://localhost:3001/api/persons/1

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
    "name": "Brett Gilbert", 
    "number": "123-456-7899"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
    "name": "", 
    "number": "123-456-7899"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
    "name": "Brett Gilbert", 
    "number": ""
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
    "name": "Ada Lovelace", 
    "number": "123-456-7899"
}