GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/608847909a069a2b08e9400c

###

GET http://localhost:3001/info

###

DELETE http://localhost:3001/api/persons/609015598040bb33a01ac8c4

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
    "name": "Vlad Sputnik", 
    "number": "444-555-1234"
}

###

PUT http://localhost:3001/api/persons/608847909a069a2b08e9400c
Content-Type: application/json

{
    "name": "Brett Daniels",
    "number": "000-000-1111"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
    "name": "", 
    "number": "123-456-7899"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
    "name": "Brett Daniels", 
    "number": ""
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
    "name": "Ada Lovelace", 
    "number": "123-456-7899"
}